### ISSUE TITLE
Should MODS RDF parse out subTitle, partNumber, partName, and nonSort, or is a single string combining them sufficient?

### ISSUE THREAD

**Issue by melanieWacker** [blunalucero/MODS-RDF#1]
Current MODS RDF Ontology represents the title via MADS RDF

**Comment by cmh2166** [comment]
See minutes on title model proposal, acceptance: https://github.com/blunalucero/MODS-RDF/wiki/MODS-RDF-Working-Group-Call-11.14.14

**Comment by barmintor** [comment]
The timing of our development team collecting our thoughts about this could not be worse, it seems.

**Comment by melanieWacker** [comment]
Do you want to re-open the issue?

**Comment by barmintor** [comment]
Reading the minutes, a subtyped property to support sorting where it differs from the complete title seems like an ideal solution for us. Thumbs up!
