### ISSUE TITLE
Superfluous Wrappers or Top Level Elements

### ISSUE THREAD

**Issue by melanieWacker** [blunalucero/MODS-RDF#10]
Wrappers (or top level elements used to group similar elements together) have been eliminated for <originInfo> and <physicalDescription> The individual elements are now represented as direct properties.
For more background see: 
Development of a MODS RDF Ontology: Discussion Points
Ray Denenberg, Library of Congress, November 4, 2013
1) Are there use cases that would lead us to carry those wrappers over?
2) Are there other wrappers that can be eliminated?

**Comment by melanieWacker** [comment]
Question: What should we name that new event superclass that is going to take the place of originInfo? If we just call it modsrdf:Event that seems a bit broad.

**Comment by raydAtLC** [comment]
We should not call it event.   In BIBFRAME it's event but that's going to change at some point (hopefully soon) when we introduce the concept of an event, as in a performance, etc.  

We need another term, one that generalizes production, publication, distribution and manufacture. Even marc never came up with a term it just calls it "production, publication, distribution and manufacture".      I have been struggling  to come up with a term for a long time. 

 How about "action"?

Ray
________________________________________

**Comment by melanieWacker** [comment]
Thinking that "action" could potentially get interpreted to include other kinds of of actions, such as preservation action taken. The original "mods:originInfo" was actually not a bad solution as a name for this. Maybe "ResourceOrigin"?

**Comment by raydAtLC** [comment]
How about "originationEvent"?
________________________________________

**Comment by melanieWacker** [comment]
That sounds good.
