### ISSUE TITLE
[xsl] Stylesheet broken

### ISSUE THREAD

**Issue by davide-romanini** [blunalucero/MODS-RDF#29]
Trying to use the xsl with saxon gives:

Error on line 11 column 31 of MODS_RDF_Stylesheet.xsl:
  SXXP0003: Error reported by XML parser: The prefix "xsl" for element "xsl:stylesheet" is not bound.
org.xml.sax.SAXParseException: The prefix "xsl" for element "xsl:stylesheet" is not bound.

The xsl linked at http://www.loc.gov/standards/mods/modsrdf/xsl-files/modsrdf.xsl seems a bit different from the one on this repository.

**Comment by cmh2166** [comment]
Hi! thanks for bringing this up.

We lost the namespace declarations somewhere in the shuffle; they've been added back. The XSLT works for me now, but let me know if it works for you too before I close the issue.

**Comment by davide-romanini** [comment]
Now it works. There are other small issues with namespaces for specific elements, but you can close this one.

**Comment by cmh2166** [comment]
Thanks Davide. I'm aware of some other issues in that stylesheet, but my attention is primarily on trying to finish the first draft of stylesheet based on the updates to MODS RDF discussed in this repos' other issues. 

However, I don't want it to limit use of this stylesheet in the present. I appreciate your patches, and I'll try to spend some time tidying things up in this stylesheet in the next week or so.

Thanks!
